[shell]
program = "/bin/zsh"

[window]

[font]
normal.family = "FiraCode Nerd Font"
normal.style = "Regular"
size = 14

[selection]
save_to_clipboard = true

[colors]

[mouse]
bindings = [
{ mouse = "Right", mods = "Shift", action = "Paste" },
{ mouse = "Left", mods = "Shift", action = "Copy" },
]

[keyboard]
